apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: bwqvj55ja-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bwqvj55ja-python 
  name: bwqvj55ja-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bwqvj55ja-python
    weight: 100 
