apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bwqvj55ja-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bwqvj55ja-python 
  name: bwqvj55ja-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bwqvj55ja-python 
